version: '3.9'

services:
  php:
    container_name: technical-test-annexx
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
        target: base
    ports:
        - "8080:80"
    volumes:
        - ./src/:/var/www/html